# Generated by Django 3.0.2 on 2020-01-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Profile',
            new_name='profile',
        ),
    ]
